export const TIMEZONES = [
  { id: "UTC", label: "(UTC) Coordinated Universal Time" },
  { id: "Etc/GMT+12", label: "(UTC-12:00) International Date Line West" },
  { id: "Pacific/Pago_Pago", label: "(UTC-11:00) Samoa" },
  { id: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii" },
  { id: "America/Anchorage", label: "(UTC-09:00) Alaska" },
  {
    id: "America/Los_Angeles",
    label: "(UTC-08:00) Pacific Time (US & Canada)",
  },
  { id: "America/Denver", label: "(UTC-07:00) Mountain Time (US & Canada)" },
  { id: "America/Chihuahua", label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan" },
  { id: "America/Phoenix", label: "(UTC-07:00) Arizona" },
  { id: "America/Chicago", label: "(UTC-06:00) Central Time (US & Canada)" },
  {
    id: "America/Mexico_City",
    label: "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
  },
  { id: "America/Regina", label: "(UTC-06:00) Saskatchewan" },
  { id: "America/Belize", label: "(UTC-06:00) Central America" },
  { id: "America/New_York", label: "(UTC-05:00) Eastern Time (US & Canada)" },
  { id: "America/Bogota", label: "(UTC-05:00) Bogota, Lima, Quito" },
  { id: "America/Indiana/Indianapolis", label: "(UTC-05:00) Indiana (East)" },
  { id: "America/Halifax", label: "(UTC-04:00) Atlantic Time (Canada)" },
  { id: "America/Caracas", label: "(UTC-04:00) Caracas, La Paz" },
  { id: "America/Guyana", label: "(UTC-04:00) Guyana" },
  { id: "America/Santiago", label: "(UTC-04:00) Santiago" },
  { id: "America/St_Johns", label: "(UTC-03:30) Newfoundland" },
  { id: "America/Sao_Paulo", label: "(UTC-03:00) Brasilia" },
  {
    id: "America/Argentina/Buenos_Aires",
    label: "(UTC-03:00) Buenos Aires, Georgetown",
  },
  { id: "America/Godthab", label: "(UTC-03:00) Greenland" },
  { id: "Atlantic/South_Georgia", label: "(UTC-02:00) Mid-Atlantic" },
  { id: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { id: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde Is." },
  { id: "Africa/Casablanca", label: "(UTC) Casablanca, Monrovia" },
  { id: "Europe/London", label: "(UTC) London, Edinburgh, Dublin" },
  { id: "Africa/Algiers", label: "(UTC+01:00) West Central Africa" },
  { id: "Africa/Windhoek", label: "(UTC+01:00) Windhoek" },
  {
    id: "Europe/Amsterdam",
    label: "(UTC+02:00) Amsterdam, Berlin, Rome, Stockholm, Vienna",
  },
  {
    id: "Europe/Belgrade",
    label: "(UTC+02:00) Belgrade, Budapest, Ljubljana, Prague",
  },
  {
    id: "Europe/Brussels",
    label: "(UTC+02:00) Brussels, Copenhagen, Madrid, Paris",
  },
  { id: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { id: "Africa/Johannesburg", label: "(UTC+02:00) Harare, Pretoria" },
  { id: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem" },
  { id: "Europe/Minsk", label: "(UTC+03:00) Minsk" },
  { id: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
  { id: "Asia/Kuwait", label: "(UTC+03:00) Kuwait, Riyadh" },
  {
    id: "Europe/Moscow",
    label: "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
  },
  { id: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { id: "Asia/Tbilisi", label: "(UTC+04:00) Tbilisi" },
  { id: "Asia/Yerevan", label: "(UTC+04:00) Yerevan" },
  { id: "Asia/Baku", label: "(UTC+04:00) Baku" },
  { id: "Asia/Dubai", label: "(UTC+04:00) Abu Dhabi, Muscat" },
  { id: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
  { id: "Asia/Tehran", label: "(UTC+05:30) Tehran" },
  { id: "Asia/Yekaterinburg", label: "(UTC+05:00) Yekaterinburg" },
  { id: "Asia/Karachi", label: "(UTC+05:00) Islamabad, Karachi, Tashkent" },
  {
    id: "Asia/Kolkata",
    label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
  },
  { id: "Asia/Colombo", label: "(UTC+05:30) Sri Jayawardenapura" },
  { id: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { id: "Asia/Almaty", label: "(UTC+06:00) Almaty, Novosibirsk" },
  { id: "Asia/Dhaka", label: "(UTC+06:00) Astana, Dhaka" },
  { id: "Asia/Rangoon", label: "(UTC+06:30) Yangon (Rangoon)" },
  { id: "Asia/Bangkok", label: "(UTC+07:00) Bangkok, Hanoi, Jakarta" },
  { id: "Asia/Krasnoyarsk", label: "(UTC+07:00) Krasnoyarsk" },
  {
    id: "Asia/Hong_Kong",
    label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
  },
  { id: "Asia/Irkutsk", label: "(UTC+08:00) Irkutsk, Ulaan Bataar" },
  { id: "Australia/Perth", label: "(UTC+08:00) Perth" },
  { id: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur, Singapore" },
  { id: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { id: "Asia/Tokyo", label: "(UTC+09:00) Osaka, Sapporo, Tokyo" },
  { id: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { id: "Asia/Yakutsk", label: "(UTC+09:00) Yakutsk" },
  { id: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { id: "Australia/Darwin", label: "(UTC+09:30) Darwin" },
  { id: "Australia/Brisbane", label: "(UTC+10:00) Brisbane, Guam" },
  { id: "Australia/Sydney", label: "(UTC+10:00) Canberra, Melbourne, Sydney" },
  {
    id: "Pacific/Guadalcanal",
    label: "(UTC+11:00) Solomon Is., New Caledonia",
  },
  { id: "Asia/Vladivostok", label: "(UTC+11:00) Vladivostok" },
  { id: "Pacific/Auckland", label: "(UTC+12:00) Auckland, Wellington" },
  { id: "Pacific/Fiji", label: "(UTC+12:00) Fiji, Kamchatka, Marshall Is." },
  { id: "Pacific/Tongatapu", label: "(UTC+13:00) Nuku'alofa" },
];
