version: "3.8"

services:
  db-test:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: scheduler_test
    ports:
      - "15432:5432"
